[Interface]
PrivateKey = <ВСТАВЬ_ПРИВАТНЫЙ_КЛЮЧ_KEENETIC>
Address = 10.8.0.2/24

[Peer]
PublicKey = a7koIxp+5AJf+NF4mpexKcX0B0c9eZomIxRBAiCy6kQ=
Endpoint = 104.171.139.250:51820
AllowedIPs = 10.8.0.1/32
PersistentKeepalive = 25
